# -*- coding: utf-8 -*-
"""MIOTESTE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154r-vsN8hm6qT1reiZAJ9aTvGcq8GtPU
"""

import matplotlib.pyplot as plt 

#declarando variaveis 
pontuacao = 0
respondido = True
lista_nomes = []
lista_idade = []
lista_ranking = []
sem_risco = []
tendencia = []
risco_medio = []
risco_grave = []

#--------------------------------------
#construindo funções

def grava_nome(nome):
  lista_nomes.append(nome)
  
def idade_pontuacao(idade):
  lista_idade.append(idade)
  global pontuacao
  if idade <=30:
    pontuacao = pontuacao
  elif idade >30 and idade <=50:
    pontuacao = pontuacao + 5
  elif idade >50:  
    pontuacao = pontuacao +10
      
    
def avalia_risco():
  global pontuacao
  lista_ranking.append(pontuacao)
  if pontuacao <=15:
    print(nome, ",", "Fico feliz em saber que você não está em nenhuma zona de risco! Continue assim!")
    sem_risco.append(nome)
  elif pontuacao >15 and pontuacao <30:
    print(nome, ",", "Olha, você apresenta uma tendência, nada preocupante, mas é melhor cuidar né?")
    tendencia.append(nome)
  elif pontuacao >=30 and pontuacao <=45:
    print(nome, "," , "Um pouco preocupante, é melhor recorrer a um profissional de saúde e cuidar!")
    risco_medio.append(nome)
  elif pontuacao >45:
    print(nome, ",", "Você deveria ir agora atrás de um médico, sua vida vale mais do que qualquer coisa!")
    risco_grave.append(nome)
  else:
    print("Não consigo interpretar seus dados... um momento!")
    
    
def avalia_pergunta(questao):
  global pontuacao
  global respondido
  if questao == 'S':
    pontuacao = pontuacao +10
  elif questao == 'N':
    pontuacao = pontuacao
  else:
    respondido = False 

def avalia_pergunta_N(questao_n):
  global pontuacao
  global respondido
  if questao_n == 'S':
    pontuacao = pontuacao
  elif questao_n == 'N':
    pontuacao = pontuacao+10
  else:
    respondido = False
    
#--------------------------------------------
#iniciando programação estruturada
       

while True:
  
  
  print("--------------- Bem Vindo ao MIOTESTE -------------- ")
  print("Aqui vamos analisar se você possui risco ou tendência a um ataque cardiaco!!")
  print("Assim que o teste for concluido o sistema irá iniciar para um novo usuário, caso queira sair digite 'DADOS' ")
  print("-------------------------------------------------------")
  print("Para começar, informe seu nome:")
  nome = input("")
  if nome != 'DADOS':
    grava_nome(nome)
    print("Olá,", nome)
    print("Vamos continuar.. Informe sua idade:")
    idade = int(input())
    idade_pontuacao(idade)
    print("Certo, já temos a sua idade e seu nome, agora responda a 5 questões simples..")
    print("-------------------------------------------------------")
    print(nome,",","Você fuma ou é ex fumante? - 'S' para SIM ou 'N' para não!" )
    questao = input("").upper()
    avalia_pergunta(questao)
    if respondido == False:
      print("Resposta fora dos padrões, encerrando teste sem resultados! ")
      print("-------------------------------------------------------------")
      break
    else:
      
      
      print("Ótimo!")
      print(nome,"," " Na sua familia existe histórico de ataques cárdiacos? - 'S' para SIM ou 'N' para não!")
      questao = input("").upper()
      avalia_pergunta(questao)
      if respondido == False:
        print("Resposta fora dos padrões, encerrando teste sem resultados! ")
        print("-------------------------------------------------------------")
        break
      else:
        print("Estamos indo bem")
        print(nome,"," " Você pratica atividades físicas com certa frequência? - 'S' para SIM ou 'N para não!' ")
        questao_n = input("").upper()
        avalia_pergunta_N(questao_n)
        if respondido == False:
          print("Resposta fora dos padrões, encerrando teste sem resultados! ")
          print("-------------------------------------------------------------")
          break
        else:
          print("")
          print("Estamos chegando ao fim, só me diz, você está acima do peso? - 'S para SIM ou 'N' para não!")
          questao = input("").upper()
          avalia_pergunta(questao)
          if respondido == False:
            print("Resposta fora dos padrões, encerrando teste sem resultados! ")
            print("-------------------------------------------------------------")
            break
          else:
            print("Por ultimo, você passa por situações estressantes ou desgastantes no seu dia a dia ? - 'S' para SIM ou 'N' para não!")
            questao = input("").upper()
            avalia_pergunta(questao)
            if respondido == False:
              print("Resposta fora dos padrões, encerrando teste sem resultados! ")
              print("-------------------------------------------------------------")
              break
            else:
              print("-------------------------------------------------")
              print("Obrigado por participar do teste, exibindo seus resultados...")
              print("")
              print("Participante: ", nome)
              print("Idade: ", idade)
              print("Com base nos dados coletados o seu score foi de: ", pontuacao)
              avalia_risco()
              print("----------------------------------------------------")
              print("No nosso teste, você pontua de 0 a 60, quanto maior, maior o seu risco. Levamos em conta alguns dados disponibilizados no site:")
              print("www.cardiometro.com.br")
              print("-----------------------------------------------------")
              print("-----------------------------------------------------")
              pontuacao = 0 
  else:

        print("=============================================================")
        print("Você solicitou o encerramento do programa e a coleta de dados")
        print("=============================================================")
        print("Apresentando nomes que fizeram o teste")
        for n, i in enumerate(lista_nomes):
          print(n,i)

        print("==============================================================")
        print("Total de:" , len(lista_nomes), "usuarios")
        print("==============================================================")
        print("Usuarios que não apresentam risco:")
        print(sem_risco)
        print("==============================================================")
        print("Usuarios com tendência: ")
        print(tendencia)
        print("==============================================================")
        print("Usuarios com risco medio: ")
        print(risco_medio)
        print("==============================================================")
        print("Usuarios com risco grave: ")
        print(risco_grave)
        print("==============================================================")
        print("Idade dos usuarios que realizaram o teste: ")
        print(lista_nomes)
        print(lista_idade)
        print("==============================================================")
        print("Pontuação de Cada:")
        print(lista_ranking)
        print("==============================================================")
        
        plt.bar(lista_nomes, lista_ranking, color='green')
        plt.ylabel("Usuários e Pontuação")
        plt.xlabel("Risco de menor para o maior")
        plt.title("0-60")
        plt.show()
        break